import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth/AuthContext";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  style: ["italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ScrollArea className="h-screen w-screen">
        <body
          className={`${inter.variable} ${lora.variable} font-sans antialiased`}
        >
          <AuthProvider>{children}</AuthProvider>
        </body>
      </ScrollArea>
    </html>
  );
}
